name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: clang-18
      CXX: clang++-18

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup LLVM
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: 18

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Configure with CMake (use clang++-18)
      run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=ReleaseWithDebInfo -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18

    - name: Build with CMake
      run: cmake --build build 

    - name: Run tests
      run: cmake --build build --target tests
